"""Added table orders

Revision ID: 25b809330ee8
Revises: 4e0a550a8c42
Create Date: 2025-05-09 23:10:42.486469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b809330ee8'
down_revision: Union[str, None] = '4e0a550a8c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'telegram',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'telegram',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
