"""Added content table

Revision ID: 9fdda028aa3c
Revises: fee3df25c840
Create Date: 2025-05-25 14:12:10.105947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdda028aa3c'
down_revision: Union[str, None] = 'fee3df25c840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'banner_first_frame_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'banner_first_frame_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'banner_first_frame_button',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'banner_second_frame_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'banner_second_frame_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'banner_second_frame_button',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'catalog_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'catalog_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_first_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_first_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_second_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_second_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_third_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_third_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_four_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'reasons_four_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'individual_order_sub',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'individual_order_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'individual_order_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'individual_order_button',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_first_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_first_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_second_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_second_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_third_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_third_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_four_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'steps_four_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'contacts_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'contacts_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'contacts_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'contacts_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('content', 'contacts_telegram',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'contacts_telegram',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'contacts_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'contacts_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'contacts_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'contacts_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_four_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_four_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_third_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_third_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_second_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_second_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_first_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_first_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'steps_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'individual_order_button',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'individual_order_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'individual_order_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'individual_order_sub',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_four_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_four_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_third_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_third_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_second_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_second_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_first_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_first_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'reasons_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'catalog_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'catalog_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'banner_second_frame_button',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'banner_second_frame_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'banner_second_frame_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'banner_first_frame_button',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'banner_first_frame_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'banner_first_frame_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
