"""Added cascade delete

Revision ID: bc21e2a4239b
Revises: 71a0da922cad
Create Date: 2025-05-09 18:26:01.065038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc21e2a4239b'
down_revision: Union[str, None] = '71a0da922cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_depth_product_id_fkey', 'product_depth', type_='foreignkey')
    op.create_foreign_key(None, 'product_depth', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_desk_color_product_id_fkey', 'product_desk_color', type_='foreignkey')
    op.create_foreign_key(None, 'product_desk_color', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_frame_color_product_id_fkey', 'product_frame_color', type_='foreignkey')
    op.create_foreign_key(None, 'product_frame_color', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_length_product_id_fkey', 'product_length', type_='foreignkey')
    op.create_foreign_key(None, 'product_length', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_length', type_='foreignkey')
    op.create_foreign_key('product_length_product_id_fkey', 'product_length', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_frame_color', type_='foreignkey')
    op.create_foreign_key('product_frame_color_product_id_fkey', 'product_frame_color', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_desk_color', type_='foreignkey')
    op.create_foreign_key('product_desk_color_product_id_fkey', 'product_desk_color', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_depth', type_='foreignkey')
    op.create_foreign_key('product_depth_product_id_fkey', 'product_depth', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
