"""change col name orders

Revision ID: c0cfd77d6935
Revises: ff4e0f47c569
Create Date: 2025-05-16 21:43:44.510351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cfd77d6935'
down_revision: Union[str, None] = 'ff4e0f47c569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('length', sa.String(), nullable=False))
    op.drop_column('orders', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('width', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'length')
    # ### end Alembic commands ###
