"""Added content table

Revision ID: fee3df25c840
Revises: bb901dd7de90
Create Date: 2025-05-25 13:59:04.294930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee3df25c840'
down_revision: Union[str, None] = 'bb901dd7de90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_first_frame_title', sa.String(), nullable=False),
    sa.Column('banner_first_frame_description', sa.String(), nullable=False),
    sa.Column('banner_first_frame_button', sa.String(), nullable=False),
    sa.Column('banner_second_frame_title', sa.String(), nullable=False),
    sa.Column('banner_second_frame_description', sa.String(), nullable=False),
    sa.Column('banner_second_frame_button', sa.String(), nullable=False),
    sa.Column('catalog_title', sa.String(), nullable=False),
    sa.Column('catalog_description', sa.String(), nullable=False),
    sa.Column('reasons_title', sa.String(), nullable=False),
    sa.Column('reasons_description', sa.String(), nullable=False),
    sa.Column('reasons_first_title', sa.String(), nullable=False),
    sa.Column('reasons_first_description', sa.String(), nullable=False),
    sa.Column('reasons_second_title', sa.String(), nullable=False),
    sa.Column('reasons_second_description', sa.String(), nullable=False),
    sa.Column('reasons_third_title', sa.String(), nullable=False),
    sa.Column('reasons_third_description', sa.String(), nullable=False),
    sa.Column('reasons_four_title', sa.String(), nullable=False),
    sa.Column('reasons_four_description', sa.String(), nullable=False),
    sa.Column('individual_order_sub', sa.String(), nullable=False),
    sa.Column('individual_order_title', sa.String(), nullable=False),
    sa.Column('individual_order_description', sa.String(), nullable=False),
    sa.Column('individual_order_button', sa.String(), nullable=False),
    sa.Column('steps_title', sa.String(), nullable=False),
    sa.Column('steps_first_title', sa.String(), nullable=False),
    sa.Column('steps_first_description', sa.String(), nullable=False),
    sa.Column('steps_second_title', sa.String(), nullable=False),
    sa.Column('steps_second_description', sa.String(), nullable=False),
    sa.Column('steps_third_title', sa.String(), nullable=False),
    sa.Column('steps_third_description', sa.String(), nullable=False),
    sa.Column('steps_four_title', sa.String(), nullable=False),
    sa.Column('steps_four_description', sa.String(), nullable=False),
    sa.Column('contacts_title', sa.String(), nullable=False),
    sa.Column('contacts_phone', sa.String(), nullable=False),
    sa.Column('contacts_email', sa.String(), nullable=False),
    sa.Column('contacts_address', sa.String(), nullable=False),
    sa.Column('contacts_telegram', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
