name: MAX_STOL CD

on:
  push:
    branches:
    - backend
    
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATEKEY }}
        port: 22
      
